"""
=============================================================================
  WORKSHEET GENERATOR — Claude Edition (worksheet_generator.py)
=============================================================================
  - Prompt caching for static context (macro reference + sample questions)
  - LIVE RAG RETRIEVAL from the tikz_library Supabase table
  - LATEX SANITIZER & SAFE ENCODING: Gracefully handles degree symbols and
    non-UTF-8 pdflatex log output without hard-crashing the process.
=============================================================================
"""

import os
import re
import json
import uuid
import shutil
import subprocess
import traceback
from pathlib import Path
from typing import Optional, List
from datetime import date

from pydantic import BaseModel, Field
from dotenv import load_dotenv

from google import genai
from google.genai import types as genai_types
from supabase import create_client

from adapter import normalize_student_profile

from claude_client import (
    generate_structured, generate_text,
    cached_block, plain_block,
    MODEL_SONNET, MODEL_HAIKU,
)
from curriculum_loader import build_curriculum_prompt_block

load_dotenv()

# ── Config ────────────────────────────────────────────────────────────────────
TEMPLATE_DIR        = Path(__file__).parent / "template"
JOBS_DIR            = Path(__file__).parent / "worksheet_jobs"
PROMPTS_DIR         = Path(__file__).parent / "prompts"

MAX_RETRIES         = 3
JOBS_DIR.mkdir(exist_ok=True)
PROMPTS_DIR.mkdir(exist_ok=True)

EMBED_MODEL       = "gemini-embedding-001"
EMBED_DIMENSIONS  = 768
TIKZ_MATCH_COUNT  = 4          # how many diagrams to retrieve per question
TIKZ_FETCH_COUNT  = 10         # how many candidates to pull from Supabase before filtering
TIKZ_MIN_SIMILARITY   = 0.55   # floor below which a match is considered irrelevant noise

_gemini_client   = genai.Client()
_supabase_client = create_client(os.getenv("SUPABASE_URL"), os.getenv("SUPABASE_SERVICE_ROLE_KEY"))


# ── Helper: LaTeX Sanitizer ───────────────────────────────────────────────────
def sanitize_latex(tex_code: str) -> str:
    """Sanitizes raw degree symbols to prevent pdflatex encoding errors."""
    if not tex_code:
        return ""
    # Replace raw degree symbol with proper LaTeX math-mode \circ
    tex_code = tex_code.replace("°", r"^\circ")
    tex_code = tex_code.replace(r"^\circ^\circ", r"^\circ")
    return tex_code

# ── Helper: Load Prompt Files ────────────────────────────────────────────────
def load_prompt(name: str) -> str:
    return (PROMPTS_DIR / name).read_text()

def load_prompt_dir(dirname: str) -> str:
    files = sorted((PROMPTS_DIR / dirname).glob("*.tex"))
    return "\n\n".join(f.read_text() for f in files)

# ── Static reference content — these get cached, never change per-call ───────
MACRO_REFERENCE  = load_prompt("macro_reference.md")
DIAGRAM_RULES    = load_prompt("diagram_rules.md")
SAMPLE_QUESTIONS = load_prompt("sample_questions.md")

# ============================================================================
# SECTION 1 — PYDANTIC SCHEMAS
# ============================================================================

class QuestionPlan(BaseModel):
    number:           int
    topic_aspect:     str  = Field(description="Specific aspect of the topic, e.g. 'SOH CAH TOA — finding a side'")
    difficulty:       str  = Field(description="easy / medium / hard")
    question_type:    str  = Field(description="single_part / multi_part / word_problem / diagram / table / mcq / show_that")
    marks:            int
    has_diagram:      bool
    misconception_targeted: Optional[str] = Field(default=None)
    notes:            str  = Field(default="", description="Brief generation note for the AI")

class WorksheetPlan(BaseModel):
    title:                   str
    num_questions:           int
    total_marks_estimate:    int
    difficulty_distribution: str
    pedagogical_rationale:   str  = Field(description="Why this structure suits this student")
    questions:               List[QuestionPlan]

class GeneratedQuestion(BaseModel):
    number:       Optional[int] = None
    tex_content:  str  = Field(description="Complete LaTeX content for this question, ready to \\input{}")
    marks:        int
    answer:       str  = Field(description="The correct final answer(s)")
    mark_scheme:  str  = Field(description="Mark scheme in Edexcel format: M1 for..., A1 for..., etc.")
    topic_aspect: str


# ============================================================================
# SECTION 2 — LATEX ASSEMBLY
# ============================================================================

def build_config_tex(meta: dict) -> str:
    return rf"""
% Auto-generated by Cloud LearnX Worksheet Generator
\newcommand{{\examDate}}{{{meta['date']}}}
\newcommand{{\examBoard}}{{{meta['board']}}}
\newcommand{{\examSubject}}{{{meta['subject']}}}
\newcommand{{\examPaper}}{{{meta['paper_title']}}}
\newcommand{{\examTier}}{{{meta['tier']}}}
\newcommand{{\examCode}}{{{meta['code']}}}
\newcommand{{\examTime}}{{{meta['time']}}}
\newcommand{{\totalMarks}}{{\total{{totalmarks}}}}
"""


def build_main_tex(num_questions: int, title: str) -> str:
    question_inputs = "\n".join([
        f"\\input{{questions/q{i}}}\n\\clearpage" if i < num_questions
        else f"\\input{{questions/q{i}}}"
        for i in range(1, num_questions + 1)
    ])
    return rf"""\documentclass[11pt]{{article}}
\input{{layout/packages}}
\input{{config}}
\input{{layout/macros}}

\renewcommand{{\familydefault}}{{\sfdefault}}

\newcounter{{totalmarks}}
\newcounter{{questionmarks}}
\newcounter{{questionNum}}
\regtotcounter{{totalmarks}}

\begin{{document}}
\input{{cover}}
\newpage

\booltrue{{drawborder}}
\newgeometry{{left=0.6in, right=0.6in, top=2cm, bottom=2cm}}
\pagestyle{{plain}}

\firstpageheader{{ALL}}

{question_inputs}

\paperTotal
\end{{document}}
"""


def build_cover_tex(student_name: str, worksheet_title: str) -> str:
    return rf"""
\pagestyle{{empty}}
\begin{{center}}
    \vspace*{{2cm}}
    {{\Huge \textbf{{\examBoard}}}} \\[5mm]
    {{\LARGE \textbf{{\examSubject}}}} \\[3mm]
    {{\Large \examPaper}} \\[8mm]
    \begin{{tcolorbox}}[colback=white, colframe=black, arc=4mm, width=0.7\textwidth,
                       boxrule=1.5pt, top=4mm, bottom=4mm]
        \centering
        {{\large \textbf{{Student:}}}} {student_name} \\[3mm]
        {{\large \textbf{{Date:}}}} \examDate \\[3mm]
        {{\large \textbf{{Topic:}}}} \examTier
    \end{{tcolorbox}}
    \vspace{{5mm}}
    {{\large \textbf{{Instructions:}}}}\\[2mm]
    \begin{{itemize}}[leftmargin=3cm]
        \item Answer ALL questions.
        \item Show ALL working — method marks are awarded for correct steps.
        \item Write answers in the spaces provided.
    \end{{itemize}}
\end{{center}}
\newpage
"""


def assemble_latex_project(job_dir, meta, student_name, generated_qs, worksheet_plan):
    (job_dir / "layout").mkdir(exist_ok=True)
    (job_dir / "questions").mkdir(exist_ok=True)
    (job_dir / "assets").mkdir(exist_ok=True)

    for f in ["packages.tex", "macros.tex"]:
        src = TEMPLATE_DIR / "layout" / f
        dst = job_dir / "layout" / f
        if src.exists():
            shutil.copy(src, dst)
        else:
            print(f"  ⚠️  Template file missing: {src}")

    assets_src = TEMPLATE_DIR / "assets"
    if assets_src.exists():
        for asset in assets_src.iterdir():
            shutil.copy(asset, job_dir / "assets" / asset.name)

    (job_dir / "config.tex").write_text(build_config_tex(meta))
    (job_dir / "cover.tex").write_text(build_cover_tex(student_name, meta['paper_title']))
    (job_dir / "main.tex").write_text(build_main_tex(len(generated_qs), meta['paper_title']))

    for q in generated_qs:
        clean_tex = sanitize_latex(q.tex_content)
        (job_dir / "questions" / f"q{q.number}.tex").write_text(clean_tex)

    print(f"  ✅ LaTeX project assembled — {len(generated_qs)} questions")


# ============================================================================
# SECTION 3 — TIKZ LIBRARY RETRIEVAL
# ============================================================================

def retrieve_tikz_diagrams(query: str, n: int = TIKZ_MATCH_COUNT) -> str:
     try:
        embed_response = _gemini_client.models.embed_content(
            model=EMBED_MODEL,
            contents=query,
            config=genai_types.EmbedContentConfig(
                output_dimensionality=EMBED_DIMENSIONS,
                task_type="RETRIEVAL_QUERY",
            ),
        )
        query_embedding = embed_response.embeddings[0].values
 
        # Over-fetch, then filter client-side for similarity floor.
        results = _supabase_client.rpc("match_tikz_library", {
            "query_embedding": query_embedding,
            "match_count": TIKZ_FETCH_COUNT,
        }).execute()
 
        if not results.data:
            print(f"    ⚠️  No tikz matches found for: '{query}'")
            return ""
 
        candidates = sorted(results.data, key=lambda r: r["similarity"], reverse=True)
        selected = [r for r in candidates if r["similarity"] >= TIKZ_MIN_SIMILARITY][:n]
        dropped_low_sim = len(candidates) - len(selected)
 
        if not selected:
            print(f"    ⚠️  No tikz matches cleared similarity ≥{TIKZ_MIN_SIMILARITY} for: '{query}' "
                  f"(best available: {candidates[0]['similarity']:.2f}) — proceeding without diagram references")
            return ""
 
        context = "TIKZ DIAGRAM REFERENCE EXAMPLES (study these for style — pick the closest match and adapt, or compose a new one in the same style):\n"
        for r in selected:
            context += f"\n--- {r['filename']} (similarity {r['similarity']:.2f}) ---\n"
            context += f"% {r['description']}\n"
            context += r['tex_content'] + "\n"
 
        note = f"    📐 Retrieved {len(selected)} tikz reference(s) for: '{query}'"
        if dropped_low_sim:
            note += f" (filtered out {dropped_low_sim} below similarity floor)"
        print(note)
        return context
 
    except Exception as e:
        print(f"    ⚠️  Tikz retrieval failed: {e} — proceeding without diagram references")
        return ""

# ============================================================================
# SECTION 4 — AI PLANNING PASS
# ============================================================================

def plan_worksheet(student_profile: dict, topic: str) -> WorksheetPlan:
    print("  🧠 Normalising profile & planning worksheet structure...")

    profile = normalize_student_profile(student_profile)

    year           = profile["year"]
    weaknesses     = profile["known_misconceptions"]
    topic_scores   = profile["topic_scores"]
    error_patterns = profile["error_patterns"]
    notes          = profile["teacher_notes"]
    curriculum_id  = profile["curriculum_id"]
    interests      = profile["interests"]

    topic_score = topic_scores.get(topic) or topic_scores.get(topic.replace("_", " ").title())
    score_note  = f"Current mastery score on {topic}: {topic_score:.0%}" if topic_score is not None else "No prior data on this topic."

    curriculum_block = ""
    if curriculum_id:
        curriculum_block = build_curriculum_prompt_block(curriculum_id, topic, year)

    user_message = f"""
    You are a highly experienced mathematics tutor designing a personalised practice worksheet.

    STUDENT PROFILE:
    - Name: {profile['name']}
    - Year / Grade: Year {year}
    - Topic for this worksheet: {topic}
    - {score_note}
    - Known misconceptions: {', '.join(weaknesses) if weaknesses else 'None recorded yet'}
    - Common error patterns: {', '.join(error_patterns) if error_patterns else 'None recorded yet'}
    - Student Interests: {', '.join(interests) if interests else 'General Science'}
    - Pedagogy Notes & Avoidances: {notes or 'None'}

    {curriculum_block}

    WORKSHEET PLANNING RULES:
    - Minimum 12 questions. For Year 10+, aim for 14-18 questions.
    - Start with 2-3 confidence-building easy questions.
    - Build up through medium questions that test core method.
    - Include 2-4 challenging questions that stretch the student.
    - Include multi-part questions for complex topics.
    - If student has interests (e.g. robotics, space, gaming), weave them naturally into word problems.
    - Respect frustration triggers (e.g., if "avoid dense word problems" is specified, keep scenarios concise).
    - Vary question types: diagrams, tables, word problems, show-that, algebraic manipulation.
    - Total marks should be proportional to difficulty — typically 40-70 marks.

    Plan the complete worksheet using the tool provided.
    """

    plan = generate_structured(
        system_blocks=[plain_block("You are an expert mathematics curriculum designer.")],
        user_message=user_message,
        output_model=WorksheetPlan,
        tool_name="submit_worksheet_plan",
        model=MODEL_SONNET,
        max_tokens=4096,
    )
    print(f"  ✅ Plan: {plan.num_questions} questions, ~{plan.total_marks_estimate} marks")
    print(f"     Distribution: {plan.difficulty_distribution}")
    return plan


# ============================================================================
# SECTION 5 — AI QUESTION GENERATION PASS
# ============================================================================

def generate_question(
    q_plan:         QuestionPlan,
    topic:          str,
    student_profile: dict,
    prev_questions: List[str] = None,
) -> GeneratedQuestion:
    prev_questions = prev_questions or []
    year = student_profile.get("year", 10)

    prev_context = ""
    if prev_questions:
        prev_context = "\nQUESTIONS ALREADY GENERATED (do NOT repeat similar numbers/scenarios):\n"
        prev_context += "\n".join(f"Q{i+1}: {q}" for i, q in enumerate(prev_questions))

    interests    = student_profile.get("interests", [])
    frustrations = student_profile.get("frustration_triggers", [])
    target_grade = student_profile.get("target_grade", "")

    student_context = ""
    if interests:
        student_context += f"\nStudent interests: {', '.join(interests)}"
    if frustrations:
        student_context += f"\nAvoid (frustration triggers): {'; '.join(frustrations)}"
    if target_grade:
        student_context += f"\nTarget grade: {target_grade} — calibrate question rigour accordingly"

    curriculum_id = student_profile.get("curriculum_id")
    curriculum_block = ""
    if curriculum_id:
        curriculum_block = build_curriculum_prompt_block(curriculum_id, topic, year)

    system_blocks = [
        cached_block(MACRO_REFERENCE),
        cached_block(DIAGRAM_RULES),
        cached_block(SAMPLE_QUESTIONS),
    ]
    if curriculum_block:
        system_blocks.append(cached_block(curriculum_block))

    tikz_context = ""
    if q_plan.has_diagram:
        query = f"{topic} — {q_plan.topic_aspect}"
        tikz_context = retrieve_tikz_diagrams(query, n=TIKZ_MATCH_COUNT)

    user_message = f"""
Generate Question {q_plan.number} for a Year {year} student on the topic: {topic}

{prev_context}

STUDENT CONTEXT:{student_context if student_context else ' None recorded.'}

QUESTION SPECIFICATION:
- Topic aspect: {q_plan.topic_aspect}
- Difficulty: {q_plan.difficulty}
- Type: {q_plan.question_type}
- Marks: {q_plan.marks}
- Needs diagram: {q_plan.has_diagram}
- Misconception to target: {q_plan.misconception_targeted or 'None — general practice'}
- Notes: {q_plan.notes or 'None'}

{tikz_context}

YOUR TASK:
1. Choose concrete, realistic numbers/scenario for this question (clean numbers where possible).
2. Actually SOLVE it step by step, exactly as a student would have to work through it.
3. Check your own setup honestly:
   - Is it self-consistent (no contradictory constraints)?
   - Is it actually solvable with the information given (not under- or over-determined)?
   - Does it require genuine work matching {q_plan.marks} marks, or is the answer
     immediately obvious / directly readable without real reasoning (i.e. trivial)?
   - Does solving it actually require the misconception/method targeted, if one was specified?
4. If ANY of the above checks fail, make necessary adjustments to the numbers, scenario, or question 
   wording until it is a valid, solvable, non-trivial question.
5. If the finalized question has a diagram, calculate key_values with EVERY concrete fact needed to reproduce this 
   diagram accurately — labeled points/vertices, exact side lengths, exact angle values, exact coordinates, etc.
   Do not leave anything implicit when allocating axis limits, points on circles, length of tangents, or node directions.
   Ensure all label nodes use explicit anchor offsets (e.g., [above left], [below right]) to prevent text clipping.
6. Write the complete LaTeX for this question — everything inside a question .tex file.
7. Use ONLY the macros listed in AVAILABLE LATEX MACROS.
8. Follow the CRITICAL MACRO RULE FOR UNITS (math units must be wrapped in $...$).
9. Include generous \\vspace{{Xcm}} for working space.
10. If the question has a diagram follow ALL rules in TIKZ DIAGRAM RULES strictly.
11. For multi-part questions, use \\begin{{enumerate}} with \\item[(a)] etc.
12. Provide the final answer plainly and a mark scheme in Edexcel format (M1 for..., A1 for...).

CONTEXT NATURALNESS:
   If using student interests for context, the connection must feel ORGANIC and PLAUSIBLE.
   - Scenario must genuinely require the mathematics — not just mention the interest as decoration.
   - If the interest doesn't fit naturally, use a neutral real-world context (architecture, engineering, science).

DO NOT SCAFFOLD AWAY THE CHALLENGE:
   - Do NOT provide the key equation the student must derive.
   - Do NOT state geometric properties that the student must identify.
   - Do NOT state/suggest the theorem that the student must use.
   - The number of marks awarded must reflect the cognitive work actually required.

`tex_content` must be valid LaTeX starting with \\begin{{question}} and ending with \\end{{question}}.
"""

    q = generate_structured(
        system_blocks=system_blocks,
        user_message=user_message,
        output_model=GeneratedQuestion,
        tool_name="submit_question",
        model=MODEL_SONNET,
        max_tokens=4096,
    )
    q.number = q_plan.number
    q.tex_content = sanitize_latex(q.tex_content)
    return q


# ============================================================================
# SECTION 6 — LATEX COMPILE + FIX LOOP (Targeted Error Parsing)
# ============================================================================

def compile_latex(job_dir: str):
    """
    Runs pdflatex safely using raw bytes capture to prevent UnicodeDecodeError 
    on non-UTF8 characters (like raw degree symbols 0xb0) in TeX logs.
    """
    try:
        result = subprocess.run(
            ["pdflatex", "-interaction=nonstopmode", "-halt-on-error", "main.tex"],
            cwd=job_dir,
            capture_output=True,
            text=False,  # Safe: captures raw bytes to avoid decoding crashes
            timeout=120,
        )

        stdout = result.stdout.decode("utf-8", errors="replace") if result.stdout else ""
        stderr = result.stderr.decode("utf-8", errors="replace") if result.stderr else ""

        log_content = ""
        log_file = os.path.join(job_dir, "main.log")
        if os.path.exists(log_file):
            with open(log_file, "rb") as f:
                log_content = f.read().decode("utf-8", errors="replace")

        combined_output = stdout + "\n" + stderr + "\n" + log_content
        success = (result.returncode == 0)

        return success, combined_output

    except subprocess.TimeoutExpired:
        return False, "pdflatex timed out after 120 seconds"
    except Exception as e:
        return False, f"Unexpected error during compilation: {str(e)}"


def extract_failed_question_num(log: str) -> Optional[int]:
    """Scans LaTeX log output for error lines specifically associated with question files."""
    matches = re.findall(r"\(?\.?/questions/q(\d+)\.tex", log)
    if matches:
        return int(matches[-1])
    return None


def extract_latex_errors(log: str) -> str:
    """Extracts error snippets and surrounding lines from TeX log."""
    error_lines = []
    lines = log.split("\n")
    for i, line in enumerate(lines):
        if line.startswith("!") or "Error" in line or "Undefined" in line:
            error_lines.extend(lines[max(0, i-2):min(len(lines), i+6)])
            error_lines.append("---")
    return "\n".join(error_lines[:50]) if error_lines else log[-2000:]


def fix_question_tex(q_number: int, bad_tex: str, error_log: str) -> str:
    user_message = f"""
    The LaTeX for Question {q_number} caused a compilation error.

    COMPILE ERROR:
    {error_log}

    BROKEN TEX CONTENT:
    {bad_tex}

    Fix the LaTeX so it compiles correctly.
    Common fixes:
    1. Unit arguments in macros like \\answerunit and \\answerequnit must have math symbols (e.g. ^\\circ or ^2) inside $...$ mode.
    2. TikZ angle arcs must use valid points.
    3. Ensure all environments (\\begin{{enumerate}}, \\begin{{tikzpicture}}) are properly closed with \\end{{...}}.

    Return ONLY the corrected LaTeX content for this question
    (starting with \\begin{{question}} and ending with \\end{{question}}).
    No explanation — only the fixed LaTeX.
    """
    fixed = generate_text(
        system_blocks=[cached_block(MACRO_REFERENCE), cached_block(DIAGRAM_RULES)],
        user_message=user_message,
        model=MODEL_HAIKU,
        max_tokens=4096,
        temperature=0.1,
    )
    fixed = re.sub(r"^```(?:latex)?\n?", "", fixed)
    fixed = re.sub(r"\n?```$", "", fixed)
    return sanitize_latex(fixed.strip())


from pathlib import Path
from typing import List, Set

def compile_with_fix_loop(job_dir: Path, questions: List[GeneratedQuestion]) -> bool:
    max_retries_per_q = 2
    q_attempts: Dict[int, int] = {q.number: 0 for q in questions}

    while questions:
        print(f" 🔨 Compiling document with {len(questions)} question(s)...")
        success, error_log = compile_latex(str(job_dir))
        
        if success:
            print(f" ✅ Compiled successfully with {len(questions)} question(s).")
            return True

        failed_q_num = extract_failed_question_num(error_log)
        snippet_errors = extract_latex_errors(error_log)

        if failed_q_num:
            target_q = next((q for q in questions if q.number == failed_q_num), None)
            
            if target_q:
                q_attempts[target_q.number] += 1
                q_file = job_dir / "questions" / f"q{target_q.number}.tex"
                
                # Check if we still have fix attempts left for THIS specific question
                if q_attempts[target_q.number] <= max_retries_per_q:
                    q_tex = q_file.read_text()
                    print(f" 🔧 Haiku repair attempt {q_attempts[target_q.number]}/{max_retries_per_q} for Q{target_q.number}...")
                    
                    fixed_tex = fix_question_tex(target_q.number, q_tex, snippet_errors)
                    
                    if fixed_tex and fixed_tex != q_tex:
                        q_file.write_text(fixed_tex)
                        target_q.tex_content = fixed_tex
                        continue  # Try compiling again with fixed question

                # --- DROPPING THE QUESTION ---
                print(f" 🗑️ Question {target_q.number} failed repairs. Dropping from document...")
                questions.remove(target_q)
                
                # Option A: Blank out the file so \input{questions/qX.tex} imports nothing
                q_file.write_text("% Question dropped due to compilation failure")
                
                # Option B (Recommended if you re-generate main.tex): 
                # rebuild_main_tex(job_dir, questions)
                
                continue  # Retry compilation without the broken question

        # If error couldn't be mapped to any question (e.g., main preamble error)
        print(" ⚠️ Preamble or global LaTeX error detected. Cannot resolve by dropping questions.")
        break

    return False


# ============================================================================
# SECTION 7 — MARK SCHEME ASSEMBLER
# ============================================================================

def build_mark_scheme(student_name, topic, worksheet_plan, questions) -> dict:
    plan_map = {qp.number: qp for qp in worksheet_plan.questions}

    return {
        "paper_title":    f"{topic} Worksheet — {student_name}",
        "subject":        "Mathematics",
        "generated_date": date.today().isoformat(),
        "total_marks":    sum(q.marks for q in questions),
        "questions": [
            {
                "question_number": q.number,
                "topic_aspect":    q.topic_aspect,
                "total_marks":     q.marks,
                "correct_answer":  q.answer,
                "mark_scheme":     q.mark_scheme,
                "misconception_targeted": plan_map[q.number].misconception_targeted
                                          if q.number in plan_map else None,
            }
            for q in questions
        ]
    }


# ============================================================================
# SECTION 8 — MAIN ENTRY POINT
# ============================================================================

def generate_worksheet(
    student_profile:  dict,
    topic:            str,
    output_dir:       Optional[Path] = None,
    board:            str = "Cloud LearnX",
    subject:          str = "Mathematics",
) -> dict:
    job_id  = str(uuid.uuid4())[:8]
    job_dir = JOBS_DIR / job_id
    job_dir.mkdir(parents=True)

    student_name = student_profile.get("name", "Student")
    year         = student_profile.get("year", 10)

    print(f"\n{'='*60}")
    print(f"  WORKSHEET GENERATOR (Claude Edition) — Job {job_id}")
    print(f"  Student: {student_name} | Year {year} | Topic: {topic}")
    print(f"{'='*60}")

    try:
        plan = plan_worksheet(student_profile, topic)

        questions      = []
        prev_summaries = []

        print(f"\n  Generating {plan.num_questions} questions...")
        for q_plan in plan.questions:
            print(f"  → Q{q_plan.number}: {q_plan.topic_aspect} [{q_plan.difficulty}, {q_plan.marks}m]")
            try:
                q = generate_question(
                    q_plan, topic, student_profile, prev_summaries,
                )
                questions.append(q)
                prev_summaries.append(
                    f"{q_plan.topic_aspect} — answer: {q.answer[:60]}"
                )
            except Exception as e:
                print(f"    ⚠️  Q{q_plan.number} generation failed: {e} — skipping")
                traceback.print_exc()

        if not questions:
            raise RuntimeError("No questions were generated successfully.")

        meta = {
            "date":        date.today().strftime("%d %B %Y"),
            "board":       board,
            "subject":     subject,
            "paper_title": f"{topic} — Practice Worksheet",
            "tier":        topic,
            "code":        f"Y{year}",
            "time":        f"{len(questions) * 5} minutes (approx.)",
        }

        print(f"\n  📄 Assembling LaTeX project...")
        assemble_latex_project(job_dir, meta, student_name, questions, plan)

        print(f"\n  🔨 Compiling PDF...")
        compiled = compile_with_fix_loop(job_dir, questions)
        pdf_path = job_dir / "main.pdf"

        if not compiled or not pdf_path.exists():
            raise RuntimeError("PDF compilation failed after all retry attempts.")

        mark_scheme = build_mark_scheme(student_name, topic, plan, questions)
        ms_path = job_dir / "mark_scheme.json"
        ms_path.write_text(json.dumps(mark_scheme, indent=2))

        if output_dir:
            Path(output_dir).mkdir(parents=True, exist_ok=True)
            safe_name = f"{student_name.replace(' ', '_')}_{topic.replace(' ', '_')}_{job_id}"
            final_pdf = Path(output_dir) / f"{safe_name}.pdf"
            final_ms  = Path(output_dir) / f"{safe_name}_markscheme.json"
            shutil.copy(pdf_path, final_pdf)
            shutil.copy(ms_path, final_ms)
            pdf_path = final_pdf

        print(f"\n  🎉 Worksheet complete!")
        print(f"     PDF:         {pdf_path}")
        print(f"     Questions:   {len(questions)}")
        print(f"     Total marks: {sum(q.marks for q in questions)}")

        return {
            "pdf_path": str(pdf_path), "mark_scheme": mark_scheme,
            "plan": plan.model_dump(), "job_id": job_id,
            "success": True, "error": None,
        }

    except Exception as e:
        print(f"\n  ❌ Worksheet generation failed: {e}")
        traceback.print_exc()
        return {
            "pdf_path": None, "mark_scheme": None, "plan": None,
            "job_id": job_id, "success": False, "error": str(e),
        }


if __name__ == "__main__":
    import sys
    from adapter import normalize_student_profile

    student_id = sys.argv[1] if len(sys.argv) > 1 else "STU-202507-KALA"
    topic      = sys.argv[2] if len(sys.argv) > 2 else "Trigonometry"

    print(f"Loading profile for student: {student_id}")

    result = _supabase_client.table("student_profiles") \
        .select("profile_data") \
        .eq("id", student_id) \
        .single() \
        .execute()

    if not result.data:
        print(f"❌ No profile found for student_id='{student_id}'")
        sys.exit(1)

    raw     = result.data["profile_data"]
    profile = normalize_student_profile(raw, topic=topic)

    print(f"  Student : {profile['name']} | Year {profile['year']}")
    print(f"  Topic   : {topic}")

    output = generate_worksheet(
        student_profile=profile,
        topic=topic,
        output_dir=Path("output_worksheets"),
    )

    if output["success"]:
        print(f"\n✅ PDF ready: {output['pdf_path']}")
    else:
        print(f"\n❌ Failed: {output['error']}")